Data:
  data_root: /share/home/orfu/DeepLearning/Dataset/PrivateDataset/FSS-Datasets/VOC2012
  base_data_root: /share/home/orfu/DeepLearning/Dataset/PrivateDataset/FSS-Datasets/VOC2012/base_annotation
  train_list: /share/home/orfu/DeepLearning/Dataset/PrivateDataset/FSS-Datasets/lists/pascal/voc_sbd_merge_noduplicate.txt
  val_list: /share/home/orfu/DeepLearning/Dataset/PrivateDataset/FSS-Datasets/lists/pascal/val.txt
  logpath: /share/home/orfu/DeepLearning/logs/CAM_BAM
  classes: 2

Train:
  # Aug
  train_h: 473
  train_w: 473
  val_size: 473
  scale_min: 0.9  # minimum random scale
  scale_max: 1.1 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  TTA: True
  ignore_label: 255
  padding_label: 255
  # Dataset & Mode
  shot: 5
  data_set: 'pascal'
  use_split_coco: False # True means FWB setting
  # Optimizer
  batch_size: 8 # batch size for training (bs8 for 1GPU)
  base_lr: 5.e-4
  epochs: 300
  start_epoch: 0
  stop_interval: 300 # stop when the best result is not updated for "stop_interval" epochs, =epochs means cancel early stop
  SGD: True
  index_split: -1 # index for determining the params group with 10x learning rate
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.0001
  warmup: False
  # Viz & Save & Resume
  print_freq: 10
  save_freq: 10
  resume:  # path to latest checkpoint (default: none, such as epoch_10.pth)  
  # Validate
  evaluate: True
  SubEpoch_val: True # val at the half epoch
  fix_random_seed_val: True
  resized_val: True
  ori_resize: False # resize to square
  vis: True
  # Else
  workers: 8
  fix_bn: True
  manual_seed: 324
  seed_deterministic: False
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  val_num: 10

Method:
  layers: 101
  vgg: False
  arch: 'BAM'   # model name
  decoder_block_num: 5
  cross_block_num: 4
  dropout: 0.2
  head: 1
  aux_weight1: 1.0
  aux_weight2: 1.0
  low_fea: 'layer2'  # low_fea for computing the Gram matrix
  kshot_trans_dim: 2 # K-shot dimensionality reduction
  merge: 'final'     # fusion scheme for GFSS ('base' Eq(S1) | 'final' Eq(18) )
  merge_tau: 0.9     # fusion threshold tau

Test_Finetune:
  weight:  # load weight for fine-tuning or testing (such as train_epoch_107_0.6897.pth)
  ann_type: 'mask' # mask/bbox

